### ISSUE TITLE
Sigmoid activation for embedding layers

### ISSUE THREAD

**Issue by jmharkins** [airalcorn2/batter-pitcher-2vec#1]
Hey Michael,

I enjoyed your presentation of this project at Sloan this year, and it's great that you posted the code up here, so thanks for that! I was revisiting it recently and I was wondering if there was any specific reason you choice sigmoid activation functions for the batter/pitcher embedding layers. Is this a typical feature of embedding layers? The only reason I could think of outside of the optimization of the network itself would be to have these embeddings be on a uniform scale for the sake of comparison and analysis after these parameters had been learned. I'm a relative novice when it comes to Neural Networks so any insight here would be greatly appreciated.

Thanks,
Johannes

**Comment by airalcorn2** [comment]
Hi, Johannes.

>The only reason I could think of outside of the optimization of the network itself would be to have these embeddings be on a uniform scale for the sake of comparison and analysis after these parameters had been learned.

Your reason is correct. I wanted to place the players in a unit hypercube to potentially help with interpreting the embeddings. Putting the features on a scale from zero to one made them feel a little like the skill sliders in, e.g., Madden to me.

**Comment by jmharkins** [comment]
Awesome, thanks for the reply, and nice work on the project!
